### ISSUE TITLE
god job with this mod!

### ISSUE THREAD

**Issue by MrCook1es** [PipeDeveloper/XmrigCC-MOD#1]
> Pause mining when Task Manager is oppen
> 
> *    Resume mining when Task Manager is closed

I wanted to ask you, where did you configure the part that sends mining into "pause mode" when you open the "task manager"?

Thanks and great work!

**Comment by PipeDeveloper** [comment]
Hello @MrCook1es.

The script to pause taskmanager is on the file App.cpp is easy to find. But is only a windows call function.

**Comment by PipeDeveloper** [comment]
Im sorry if i didnt answer before, i was very bussy
