### ISSUE TITLE
Violations of GPL

### ISSUE THREAD

**Issue by Bendr0id** [PipeDeveloper/XmrigCC-MOD#3]
Seems that you are violating the GPL license by removing all the license and copyright informations.

Please recover these Infos.

**Comment by PipeDeveloper** [comment]
Hello @Bendr0id Yes, you are right and im very sorry. I wanted to use your proyect as a model but as a petition of an user i made a whole remake of the full software and i deleted the copyright info, and i uploaded without it (just copy paste to all files is very but very tired)

I want to make a branch of this actual proyect and make a new one with the copy right information (as the master branch oviusly). Thanks for advice and again sorry for it, i'll fix it as soon as i can. Also i would like to thanks you for your great proyect, i learned too much, you are awesome!!

**Comment by PipeDeveloper** [comment]
Sorry for any inconvenience. Copyrights are added to all files. I apreciate all of your work!
